FROM ubuntu:22.04

RUN apt-get update \
    && apt-get -y upgrade && DEBIAN_FRONTEND=noninteractive apt-get -y install \
    build-essential libprotobuf-dev libboost-dev openssl protobuf-compiler liblz4-tool zstd \
    lsb-release ca-certificates apt-transport-https software-properties-common \
    && add-apt-repository ppa:ondrej/php

# Install apache, PHP, and supplimentary programs
RUN apt-get update \
    && apt-get -y upgrade \
    && DEBIAN_FRONTEND=noninteractive apt-get -y install \
    apache2 php8.2-cli php8.2-dev php8.2-mysql php8.2-pdo php8.2-xml libapache2-mod-php8.2 curl \
    php-xml php8.2-gd php-curl php8.2-mbstring nano git zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Enable apache mods.
RUN a2enmod php8.2
RUN a2enmod rewrite

RUN pecl install mysql_xdevapi

# Create its own ini file
RUN echo "extension=mysql_xdevapi.so" > /etc/php/8.2/mods-available/mysql_xdevapi.ini

# Use the 'phpenmod' command (note: it's Debian/Ubuntu specific)
RUN phpenmod -v 8.2 -s ALL mysql_xdevapi

# Update the PHP.ini file, enable <? ?> tags and quieten logging.
#RUN sed -i "s/short_open_tag = Off/short_open_tag = On/" /etc/php/7.0/apache2/php.ini
#RUN sed -i "s/error_reporting = .*$/error_reporting = E_ERROR | E_WARNING | E_PARSE/" /etc/php/7.0/apache2/php.ini

# Configure Locales
#RUN locale-gen en_US.UTF-8
#ENV LANG en_US.UTF-8
#ENV LANGUAGE en_US:en
#ENV LC_ALL en_US.UTF-8

# Manually set up the apache environment variables
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

# Expose apache.
EXPOSE 80

# Update the default apache site with the config we created.
ADD apache-config.conf /etc/apache2/sites-enabled/000-default.conf

ADD php.ini /etc/php/7.0/apache2/php.ini

# By default start up apache in the foreground, override with /bin/bash for interative.
CMD /usr/sbin/apache2ctl -D FOREGROUND