version: '3'

services:

  apache-server:
      build:
        context: ./docker/apache
      ports:
        - ${APP_PORT}
#      - "443:443"
#      environment:
#        MYSQL_DATABASE: ${DATABASE_NAME}
#        MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      restart: always
      volumes:
        - ./www:/var/www/html
#      links:
#      - mysql-server